<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Berita;

class BeritaSeeder extends Seeder
{
    public function run(): void
    {
        $beritas = [
            [
                'title' => 'PII Gelar Kongres Nasional Ke-32 di Jakarta',
                'category' => 'artikel_teknik',
                'sub_category' => 'Kegiatan Nasional',
                'author' => 'Humas PII',
                'excerpt' => 'Persatuan Insinyur Indonesia sukses menyelenggarakan Kongres Nasional ke-32 yang dihadiri oleh lebih dari 500 insinyur dari seluruh Indonesia.',
                'content' => '<p>Persatuan Insinyur Indonesia sukses menyelenggarakan Kongres Nasional ke-32 yang dihadiri oleh lebih dari 500 insinyur dari seluruh Indonesia. Acara ini membahas berbagai isu strategis terkait pembangunan nasional dan peran insinyur dalam era digital.</p><p>Kongres yang berlangsung selama tiga hari ini menghasilkan beberapa rekomendasi penting untuk pengembangan profesi keinsinyuran di Indonesia. Para peserta aktif berdiskusi tentang tantangan dan peluang yang dihadapi oleh insinyur Indonesia di era globalisasi.</p><p>"Kita harus memastikan bahwa insinyur Indonesia siap menghadapi revolusi industri 4.0. Ini bukan lagi tentang pilihan, tapi keharusan," ujar Ketua Umum PII dalam sambutannya.</p>',
                'image' => 'https://images.unsplash.com/photo-1540575467063-178a50c2df87?w=800&q=80',
                'published_at' => now()->subDays(2),
                'is_active' => true,
            ],
            [
                'title' => 'Peluncuran Program Sertifikasi Baru untuk Insinyur Muda',
                'category' => 'regulasi',
                'sub_category' => 'Sertifikasi',
                'author' => 'Divisi Pendidikan',
                'excerpt' => 'PII meluncurkan program sertifikasi baru yang dirancang khusus untuk insinyur muda untuk meningkatkan daya saing di pasar kerja.',
                'content' => '<p>PII meluncurkan program sertifikasi baru yang dirancang khusus untuk insinyur muda untuk meningkatkan daya saing di pasar kerja. Program ini mencakup berbagai kompetensi teknis dan soft skills yang dibutuhkan di industri 4.0.</p><p>Program sertifikasi ini terdiri dari beberapa level, mulai dari junior engineer hingga professional engineer. Setiap level memiliki kriteria dan standar kompetensi yang harus dipenuhi oleh peserta.</p><p>"Dengan adanya program ini, kami berharap dapat meningkatkan kualitas insinyur Indonesia secara menyeluruh," jelas Direktur Pendidikan PII.</p>',
                'image' => 'https://images.unsplash.com/photo-1522202176988-66273c2fd55f?w=800&q=80',
                'published_at' => now()->subDays(5),
                'is_active' => true,
            ],
            [
                'title' => 'Kerjasama PII dengan Berbagai Universitas',
                'category' => 'inovasi',
                'sub_category' => 'Kerjasama',
                'author' => 'Kerjasama Luar Negeri',
                'excerpt' => 'PII menjalin kerjasama strategis dengan universitas-universitas terkemuka untuk pengembangan pendidikan keinsinyuran.',
                'content' => '<p>PII menjalin kerjasama strategis dengan universitas-universitas terkemuka untuk pengembangan pendidikan keinsinyuran. Kerjasama ini meliputi pertukaran mahasiswa, joint research, dan program magang.</p><p>Beberapa universitas yang telah menjalin kerjasama meliputi ITB, UI, UGM, dan ITS. Kerjasama ini diharapkan dapat menjembatani dunia akademik dengan dunia industri.</p><p>"Kolaborasi antara perguruan tinggi dan organisasi profesi sangat penting untuk memastikan lulusan siap kerja," ujar salah satu dekan teknik yang hadir dalam penandatanganan MoU.</p>',
                'image' => 'https://images.unsplash.com/photo-1562774053-701939374585?w=800&q=80',
                'published_at' => now()->subDays(7),
                'is_active' => true,
            ],
            [
                'title' => 'Seminar Nasional Teknologi Hijau 2024',
                'category' => 'inovasi',
                'sub_category' => 'Teknologi',
                'author' => 'Panitia Seminar',
                'excerpt' => 'Seminar nasional yang membahas inovasi teknologi hijau untuk mendukung pembangunan berkelanjutan di Indonesia.',
                'content' => '<p>Seminar nasional yang membahas inovasi teknologi hijau untuk mendukung pembangunan berkelanjutan di Indonesia. Hadirkan pembicara ahli dari dalam dan luar negeri.</p><p>Teknologi hijau menjadi fokus utama dalam seminar ini, mengingat komitmen Indonesia untuk mengurangi emisi karbon. Berbagai solusi inovatif dari insinyur Indonesia dipresentasikan dalam acara ini.</p><p>"Insinyur memiliki peran penting dalam menciptakan solusi teknologi yang ramah lingkungan," tegas salah satu pembicara kunci.</p>',
                'image' => 'https://images.unsplash.com/photo-1497436072909-60f360e1d4b1?w=800&q=80',
                'published_at' => now()->subDays(10),
                'is_active' => true,
            ],
            [
                'title' => 'Beasiswa PII untuk Mahasiswa Teknik',
                'category' => 'artikel_teknik',
                'sub_category' => 'Pendidikan',
                'author' => 'Divisi Beasiswa',
                'excerpt' => 'PII membuka program beasiswa untuk mahasiswa teknik berprestasi dari seluruh Indonesia untuk tahun akademik 2024/2025.',
                'content' => '<p>PII membuka program beasiswa untuk mahasiswa teknik berprestasi dari seluruh Indonesia untuk tahun akademik 2024/2025. Beasiswa ini mencakup biaya pendidikan dan dukungan pengembangan karir.</p><p>Program beasiswa ini terbuka untuk mahasiswa semester 3-7 dari berbagai disiplin teknik. Seleksi dilakukan berdasarkan prestasi akademik, aktivitas organisasi, dan wawancara.</p><p>"Kami berkomitmen untuk mendukung generasi muda Indonesia yang berbakat di bidang teknik," ungkap Ketua Divisi Beasiswa PII.</p>',
                'image' => 'https://images.unsplash.com/photo-1427504494785-3a9ca7044f45?w=800&q=80',
                'published_at' => now()->subDays(14),
                'is_active' => true,
            ],
            [
                'title' => 'Perubahan Regulasi Sertifikat Kompetensi Insinyur 2024',
                'category' => 'regulasi',
                'sub_category' => 'Regulasi',
                'author' => 'Divisi Regulasi',
                'excerpt' => 'Pemerintah mengeluarkan regulasi baru terkait sertifikat kompetensi insinyur yang berlaku mulai tahun 2024.',
                'content' => '<p>Pemerintah melalui Kementerian PUPR mengeluarkan regulasi baru terkait sertifikat kompetensi insinyur yang berlaku mulai tahun 2024. Regulasi ini membawa beberapa perubahan signifikan dalam proses sertifikasi.</p><p>Beberapa poin penting dalam regulasi baru meliputi: penambahan kompetensi digital, peningkatan standar keselamatan, dan adopsi standar internasional.</p><p>PII menyambut baik regulasi ini dan berkomitmen untuk membantu anggota dalam proses transisi menuju sistem yang baru.</p>',
                'image' => 'https://images.unsplash.com/photo-1450101499163-c8848c66ca85?w=800&q=80',
                'published_at' => now()->subDays(8),
                'is_active' => true,
            ],
            [
                'title' => 'Inovasi AI dalam Perencanaan Proyek Konstruksi',
                'category' => 'inovasi',
                'sub_category' => 'Teknologi',
                'author' => 'Divisi Teknologi',
                'excerpt' => 'Pemanfaatan kecerdasan buatan (AI) semakin merambah ke dunia konstruksi, membawa efisiensi yang signifikan.',
                'content' => '<p>Pemanfaatan kecerdasan buatan (AI) semakin merambah ke dunia konstruksi, membawa efisiensi yang signifikan dalam perencanaan dan pelaksanaan proyek.</p><p>Beberapa perusahaan konstruksi besar di Indonesia telah mulai mengadopsi teknologi AI untuk optimasi jadwal, prediksi risiko, dan manajemen sumber daya.</p><p>"AI bukan pengganti insinyur, tapi alat bantu yang sangat powerful untuk meningkatkan akurasi dan efisiensi," jelas pakar konstruksi yang menjadi narasumber.</p>',
                'image' => 'https://images.unsplash.com/photo-1485827404703-89b55fcc595e?w=800&q=80',
                'published_at' => now()->subDays(3),
                'is_active' => true,
            ],
            [
                'title' => 'Masa Depan Profesi Insinyur di Era Digital',
                'category' => 'opini',
                'sub_category' => 'Opini',
                'author' => 'Prof. Dr. Ahmad Santoso',
                'excerpt' => 'Refleksi tentang bagaimana profesi keinsinyuran harus beradaptasi dengan perkembangan teknologi digital.',
                'content' => '<p>Profesi keinsinyuran sedang menghadapi titik balik yang penting. Era digital tidak hanya mengubah cara kita bekerja, tapi juga mengubah esensi dari apa yang menjadi tanggung jawab seorang insinyur.</p><p>Di masa depan, insinyur tidak hanya dituntut untuk memahami fisika dan matematika, tapi juga harus menguasai data science, pemrograman, dan berbagai soft skills baru.</p><p>Adaptasi adalah kunci. Insinyur yang mampu menggabungkan pengetahuan teknik klasik dengan keterampilan digital akan menjadi pemimpin di era baru ini.</p>',
                'image' => 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=800&q=80',
                'published_at' => now()->subDays(4),
                'is_active' => true,
            ],
            [
                'title' => 'Peran Insinyur dalam Pembangunan Berkelanjutan',
                'category' => 'opini',
                'sub_category' => 'Opini',
                'author' => 'Dr. Rina Wijaya',
                'excerpt' => 'Tanggung jawab insinyur tidak hanya menciptakan struktur yang kuat, tapi juga yang berkelanjutan bagi generasi mendatang.',
                'content' => '<p>Ketika kita berbicara tentang pembangunan berkelanjutan, peran insinyur menjadi sangat sentral. Setiap keputusan desain yang kita buat hari ini akan berdampak puluhan tahun ke depan.</p><p>Insinyur harus mulai memikirkan siklus hidup penuh dari setiap proyek, bukan hanya aspek konstruksi. Ini berarti mempertimbangkan dampak lingkungan, efisiensi energi, dan kemudahan perawatan.</p><p>Komitmen terhadap sustainability bukan lagi pilihan, tapi keharusan bagi profesi kita.</p>',
                'image' => 'https://images.unsplash.com/photo-1518173946687-a4c036bc3c95?w=800&q=80',
                'published_at' => now()->subDays(6),
                'is_active' => true,
            ],
            [
                'title' => 'Teknik Sipil dan Tantangan Perubahan Iklim',
                'category' => 'artikel_teknik',
                'sub_category' => 'Teknik Sipil',
                'author' => 'Ir. Budi Hartono, M.Eng',
                'excerpt' => 'Perubahan iklim membawa tantangan baru bagi insinyur sipil dalam merancang infrastruktur yang tangguh.',
                'content' => '<p>Perubahan iklim bukan lagi isu abstrak. Bagi insinyur sipil, ini adalah realitas yang harus dihadapi setiap hari dalam bentuk cuaca ekstrem, kenaikan muka air laut, dan perubahan pola curah hujan.</p><p>Infrastruktur yang kita bangun 20 tahun lalu mungkin tidak cukup kuat menghadapi kondisi iklim saat ini. Ini berarti kita perlu merevisi banyak standar dan spesifikasi teknis.</p><p>Resilience menjadi kata kunci dalam setiap proyek konstruksi modern. Bangunan tidak hanya harus kuat, tapi juga adaptif terhadap perubahan lingkungan.</p>',
                'image' => 'https://images.unsplash.com/photo-1504307651254-35680f356dfd?w=800&q=80',
                'published_at' => now()->subDays(9),
                'is_active' => true,
            ],
            [
                'title' => 'Transformasi Digital dalam Industri Manufaktur',
                'category' => 'inovasi',
                'sub_category' => 'Industri 4.0',
                'author' => 'Dr. Hendra Kusuma',
                'excerpt' => 'Industri manufaktur Indonesia bertransformasi menuju Industry 4.0 dengan adopsi teknologi digital.',
                'content' => '<p>Transformasi digital dalam industri manufaktur bukan lagi tren, tapi kebutuhan untuk bertahan di pasar global. Perusahaan manufaktur Indonesia mulai mengadopsi teknologi IoT, AI, dan otomatisasi.</p><p>Insinyur manufaktur memiliki peran krusial dalam memimpin transformasi ini. Mereka harus memahami tidak hanya proses produksi konvensional, tapi juga integrasi sistem digital.</p><p>"Indonesia memiliki potensi besar menjadi hub manufaktur digital di Asia Tenggara jika kita mampu mengoptimalkan SDM insinyur kita," ungkap pakar industri.</p>',
                'image' => 'https://images.unsplash.com/photo-1581092918056-0c4c3acd3789?w=800&q=80',
                'published_at' => now()->subDays(11),
                'is_active' => true,
            ],
            [
                'title' => 'Pentingnya Keselamatan Kerja di Proyek Konstruksi',
                'category' => 'regulasi',
                'sub_category' => 'K3',
                'author' => 'Divisi K3 PII',
                'excerpt' => 'Keselamatan kerja adalah prioritas utama dalam setiap proyek konstruksi untuk melindungi pekerja dan masyarakat.',
                'content' => '<p>Kecelakaan kerja di sektor konstruksi masih menjadi isu serius di Indonesia. Data menunjukkan bahwa insiden kecelakaan bisa diminimalkan dengan penerapan standar K3 yang ketat.</p><p>PII terus mendorong penerapan standar keselamatan kerja internasional dalam setiap proyek konstruksi di Indonesia. Insinyur sebagai pemimpin proyek harus menjadi role model dalam penerapan K3.</p><p>"Tidak ada proyek yang sepadan dengan nyawa manusia. K3 bukan biaya, tapi investasi," tegas Ketua Divisi K3 PII.</p>',
                'image' => 'https://images.unsplash.com/photo-1504307651254-35680f356dfd?w=800&q=80',
                'published_at' => now()->subDays(12),
                'is_active' => true,
            ],
            [
                'title' => 'Peluang Karir Insinyur di Sektor Energi Terbarukan',
                'category' => 'opini',
                'sub_category' => 'Karir',
                'author' => 'Ir. Diana Pratiwi',
                'excerpt' => 'Sektor energi terbarukan menawarkan peluang karir yang menjanjikan bagi insinyur Indonesia.',
                'content' => '<p>Transisi energi global membuka peluang besar bagi insinyur Indonesia. Sektor energi terbarukan seperti surya, angin, dan panas bumi membutuhkan banyak tenaga ahli.</p><p>Indonesia memiliki potensi energi terbarukan yang sangat besar namun belum teroptimasi. Ini adalah kesempatan emas bagi insinyur untuk berkontribusi dalam mewujudkan energi bersih nasional.</p><p>"Insinyur yang memiliki kompetensi di bidang EBT akan sangat dicari dalam 10 tahun ke depan," prediksi pakar energi.</p>',
                'image' => 'https://images.unsplash.com/photo-1509391366360-2e959784a276?w=800&q=80',
                'published_at' => now()->subDays(13),
                'is_active' => true,
            ],
            [
                'title' => 'Smart City: Masa Depan Urban Planning Indonesia',
                'category' => 'inovasi',
                'sub_category' => 'Smart City',
                'author' => 'Dr. Andi Wijaya',
                'excerpt' => 'Konsep smart city mulai diterapkan di berbagai kota Indonesia dengan integrasi teknologi digital.',
                'content' => '<p>Lebih dari 100 kota di Indonesia sedang dalam proses transformasi menuju smart city. Konsep ini mengintegrasikan teknologi IoT, big data, dan AI dalam manajemen kota.</p><p>Insinyur memiliki peran penting dalam merancang infrastruktur digital yang mendukung smart city. Mulai dari sensor networks hingga sistem manajemen lalu lintas cerdas.</p><p>"Smart city bukan hanya tentang teknologi, tapi tentang bagaimana teknologi meningkatkan kualitas hidup warga," jelas pakar urban planning.</p>',
                'image' => 'https://images.unsplash.com/photo-1573164713988-8665fc963095?w=800&q=80',
                'published_at' => now()->subDays(15),
                'is_active' => true,
            ],
            [
                'title' => 'Tantangan Insinyur dalam Pembangunan IKN',
                'category' => 'artikel_teknik',
                'sub_category' => 'Infrastruktur',
                'author' => 'Tim IKN PII',
                'excerpt' => 'Pembangunan Ibu Kota Nusantara membutuhkan peran insinyur Indonesia untuk menciptakan kota masa depan.',
                'content' => '<p>Pembangunan Ibu Kota Nusantara (IKN) adalah proyek strategis nasional yang membutuhkan kontribusi insinyur dari berbagai disiplin ilmu.</p><p>Tantangan yang dihadapi meliputi pembangunan infrastruktur yang tangguh, sistem transportasi terintegrasi, dan pengelolaan lingkungan yang berkelanjutan.</p><p>"IKN adalah laboratorium besar bagi insinyur Indonesia untuk menunjukkan kemampuan kita di kancah internasional," ujar Ketua Tim IKN PII.</p>',
                'image' => 'https://images.unsplash.com/photo-1486325212027-8081e485255e?w=800&q=80',
                'published_at' => now()->subDays(16),
                'is_active' => true,
            ],
            [
                'title' => 'Sertifikasi Profesi Insinyur: Standar Baru 2024',
                'category' => 'regulasi',
                'sub_category' => 'Sertifikasi',
                'author' => 'Badan Sertifikasi PII',
                'excerpt' => 'PII memperbarui standar sertifikasi profesi insinyur sesuai dengan perkembangan teknologi dan kebutuhan industri.',
                'content' => '<p>Standar sertifikasi profesi insinyur diperbarui untuk mengakomodasi kompetensi digital dan soft skills yang dibutuhkan di era modern.</p><p>Perubahan ini mencakup penambahan modul digital literacy, leadership, dan manajemen inovasi dalam kurikulum sertifikasi.</p><p>"Tujuannya adalah memastikan insinyur Indonesia tidak hanya kompeten secara teknis, tapi juga siap menghadapi tantangan abad 21," jelas Ketua Badan Sertifikasi.</p>',
                'image' => 'https://images.unsplash.com/photo-1554224155-6726b3ff858f?w=800&q=80',
                'published_at' => now()->subDays(17),
                'is_active' => true,
            ],
            [
                'title' => 'Inovasi Material Konstruksi Ramah Lingkungan',
                'category' => 'inovasi',
                'sub_category' => 'Material',
                'author' => 'Dr. Sari Lestari',
                'excerpt' => 'Penelitian material konstruksi ramah lingkungan menawarkan alternatif sustainable untuk pembangunan.',
                'content' => '<p>Penelitian material konstruksi ramah lingkungan terus berkembang di Indonesia. Material seperti geopolymer concrete, bambu rekayasa, dan material daur ulang mulai banyak digunakan.</p><p>Insinyur material memiliki peran penting dalam mengembangkan dan menguji material-material baru ini untuk memastikan keamanan dan kualitasnya.</p><p>"Material hijau bukan hanya tentang lingkungan, tapi juga tentang efisiensi biaya jangka panjang," ungkap peneliti material.</p>',
                'image' => 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&q=80',
                'published_at' => now()->subDays(18),
                'is_active' => true,
            ],
            [
                'title' => 'Peran Insinyur dalam Mitigasi Bencana Alam',
                'category' => 'artikel_teknik',
                'sub_category' => 'Mitigasi Bencana',
                'author' => 'Divisi Bencana Alam PII',
                'excerpt' => 'Insinyur memiliki peran krusial dalam merancang infrastruktur yang tahan bencana dan sistem peringatan dini.',
                'content' => '<p>Indonesia berada di zona rawan bencana seperti gempa, tsunami, dan banjir. Insinyur harus merancang infrastruktur yang tangguh terhadap ancaman ini.</p><p>Sistem peringatan dini, desain struktur tahan gempa, dan pengelolaan drainase adalah beberapa area di mana insinyur berkontribusi dalam mitigasi bencana.</p><p>"Setiap insinyur harus memahami risiko bencana di area proyeknya dan merancang solusi yang sesuai," tegas ahli mitigasi bencana.</p>',
                'image' => 'https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=800&q=80',
                'published_at' => now()->subDays(19),
                'is_active' => true,
            ],
            [
                'title' => 'Mentoring untuk Insinyur Muda: Program Baru PII',
                'category' => 'opini',
                'sub_category' => 'Pengembangan Karir',
                'author' => 'Divisi Pengembangan Karir',
                'excerpt' => 'PII meluncurkan program mentoring untuk menghubungkan insinyur muda dengan senior berpengalaman.',
                'content' => '<p>Program mentoring baru dari PII bertujuan menghubungkan insinyur muda dengan senior yang telah berpengalaman di bidangnya.</p><p>Setiap mentee akan dipasangkan dengan mentor yang sesuai dengan minat dan bidang keahliannya. Program ini berlangsung selama 6 bulan dengan sesi rutin.</p><p>"Mentoring adalah cara terbaik untuk mentransfer pengetahuan dan pengalaman antar generasi insinyur," jelas koordinator program.</p>',
                'image' => 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=800&q=80',
                'published_at' => now()->subDays(20),
                'is_active' => true,
            ],
            [
                'title' => 'Digital Twins dalam Manajemen Aset Infrastruktur',
                'category' => 'inovasi',
                'sub_category' => 'Teknologi Digital',
                'author' => 'Dr. Bambang Sutrisno',
                'excerpt' => 'Teknologi digital twins mulai digunakan untuk manajemen aset infrastruktur yang lebih efektif.',
                'content' => '<p>Digital twins adalah replika digital dari aset fisik yang memungkinkan monitoring dan simulasi secara real-time. Teknologi ini mulai diadopsi di Indonesia.</p><p>Insinyur dapat menggunakan digital twins untuk memprediksi kebutuhan maintenance, optimasi operasional, dan perencanaan upgrade aset.</p><p>"Digital twins mengubah cara kita mengelola infrastruktur dari reaktif menjadi prediktif," ungkap pakar teknologi.</p>',
                'image' => 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=800&q=80',
                'published_at' => now()->subDays(21),
                'is_active' => true,
            ],
            [
                'title' => 'Standar Internasional dalam Proyek Konstruksi Indonesia',
                'category' => 'regulasi',
                'sub_category' => 'Standar',
                'author' => 'Divisi Standar Teknis',
                'excerpt' => 'Adopsi standar internasional meningkatkan kualitas dan daya saing proyek konstruksi Indonesia.',
                'content' => '<p>Proyek konstruksi Indonesia semakin banyak mengadopsi standar internasional seperti ISO, ASTM, dan standar Eropa.</p><p>Penerapan standar internasional meningkatkan kualitas konstruksi dan memudahkan kolaborasi dengan perusahaan asing.</p><p>"Standar internasional bukan tentang mengikuti negara lain, tapi tentang memastikan kualitas yang setara," jelas ahli standar teknis.</p>',
                'image' => 'https://images.unsplash.com/photo-1477959858617-67f85cf4f1df?w=800&q=80',
                'published_at' => now()->subDays(22),
                'is_active' => true,
            ],
            [
                'title' => 'Peluang Riset untuk Insinyur Akademik',
                'category' => 'opini',
                'sub_category' => 'Akademik',
                'author' => 'Prof. Dr. Yuliati',
                'excerpt' => 'Insinyur akademik memiliki peluang besar untuk berkontribusi melalui riset dan publikasi ilmiah.',
                'content' => '<p>Insinyur yang berkarir di akademik memiliki peran ganda: mendidik generasi muda dan melakukan riset yang bermanfaat bagi industri.</p><p>Hibah riset dari pemerintah dan kolaborasi internasional semakin terbuka bagi peneliti Indonesia. Ini adalah kesempatan untuk meningkatkan kontribusi ilmiah.</p><p>"Riset insinyur harus relevan dengan kebutuhan industri dan masyarakat," tegas profesor riset.</p>',
                'image' => 'https://images.unsplash.com/photo-1524661135-423995f22d0b?w=800&q=80',
                'published_at' => now()->subDays(23),
                'is_active' => true,
            ],
            [
                'title' => 'Automasi dalam Proyek Konstruksi Modern',
                'category' => 'inovasi',
                'sub_category' => 'Automasi',
                'author' => 'Ir. Rudi Hartono',
                'excerpt' => 'Teknologi automasi mulai diterapkan di berbagai aspek proyek konstruksi untuk meningkatkan efisiensi.',
                'content' => '<p>Dari robotik untuk pekerjaan berbahaya hingga drone untuk survey, automasi mengubah cara proyek konstruksi dieksekusi.</p><p>Insinyur harus memahami teknologi automasi untuk dapat mengintegrasikannya dalam perencanaan dan pelaksanaan proyek.</p><p>"Automasi bukan menggantikan pekerja, tapi membuat pekerjaan lebih aman dan efisien," jelas praktisi konstruksi.</p>',
                'image' => 'https://images.unsplash.com/photo-1581092921461-eab62e97a780?w=800&q=80',
                'published_at' => now()->subDays(24),
                'is_active' => true,
            ],
            [
                'title' => 'Etika Profesi dalam Era Digital',
                'category' => 'regulasi',
                'sub_category' => 'Etika',
                'author' => 'Divisi Etika Profesi',
                'excerpt' => 'Tantangan etika baru muncul seiring dengan digitalisasi profesi keinsinyuran.',
                'content' => '<p>Era digital membawa tantangan etika baru bagi insinyur: privasi data, keamanan siber, dan transparansi algoritma.</p><p>PII terus memperbarui kode etik profesi untuk mengakomodasi isu-isu digital ini dan memberikan panduan bagi anggota.</p><p>"Etika bukan hanya tentang perilaku, tapi tentang tanggung jawab terhadap masyarakat," ungkap Ketua Divisi Etika.</p>',
                'image' => 'https://images.unsplash.com/photo-1589829545856-d10d557cf95f?w=800&q=80',
                'published_at' => now()->subDays(25),
                'is_active' => true,
            ],
            [
                'title' => 'Kolaborasi Internasional untuk Proyek Infrastruktur',
                'category' => 'artikel_teknik',
                'sub_category' => 'Kerjasama Internasional',
                'author' => 'Divisi Luar Negeri',
                'excerpt' => 'Insinyur Indonesia semakin terlibat dalam proyek infrastruktur internasional.',
                'content' => '<p>Insinyur Indonesia mulai mendapatkan pengakuan di kancah internasional dengan keterlibatan dalam proyek di berbagai negara.</p><p>Kolaborasi ini membawa pengalaman berharga dan membuka peluang untuk ekspor jasa teknik Indonesia.</p><p>"Kualitas insinyur Indonesia tidak kalah dengan negara lain. Kita hanya perlu lebih percaya diri," ujar praktisi internasional.</p>',
                'image' => 'https://images.unsplash.com/photo-1578496479531-32e296d5c6e1?w=800&q=80',
                'published_at' => now()->subDays(26),
                'is_active' => true,
            ],
            [
                'title' => 'Green Building Certification di Indonesia',
                'category' => 'inovasi',
                'sub_category' => 'Sustainability',
                'author' => 'Dr. Citra Dewi',
                'excerpt' => 'Sertifikasi green building semakin populer sebagai standar bangunan ramah lingkungan.',
                'content' => '<p>Sertifikasi green building seperti GREENSHIP dan EDGE semakin banyak dicari oleh pengembang properti di Indonesia.</p><p>Insinyur memiliki peran penting dalam merancang bangunan yang memenuhi standar green building dari efisiensi energi hingga pengelolaan air.</p><p>"Green building bukan tren, tapi kebutuhan untuk masa depan yang berkelanjutan," jelas ahli green building.</p>',
                'image' => 'https://images.unsplash.com/photo-1474487548417-781cb71495f3?w=800&q=80',
                'published_at' => now()->subDays(27),
                'is_active' => true,
            ],
            [
                'title' => 'Entrepreneurship untuk Insinyur: Menjadi Founder',
                'category' => 'opini',
                'sub_category' => 'Entrepreneurship',
                'author' => 'Ir. Denny Prasetyo',
                'excerpt' => 'Banyak insinyur sukses menjadi founder startup teknologi dan perusahaan teknik.',
                'content' => '<p>Latar belakang teknik memberikan keunggulan bagi insinyur yang ingin menjadi entrepreneur. Kemampuan problem-solving dan pemahaman teknis adalah aset berharga.</p><p>PII mendukung anggota yang ingin berwirausaha melalui program inkubasi dan mentoring khusus.</p><p>"Insinyur adalah problem solver alami. Ini adalah kualitas yang dibutuhkan entrepreneur," ungkap founder startup teknik.</p>',
                'image' => 'https://images.unsplash.com/photo-1554224155-6726b3ff858f?w=800&q=80',
                'published_at' => now()->subDays(28),
                'is_active' => true,
            ],
            [
                'title' => 'Manajemen Risiko dalam Proyek Besar',
                'category' => 'regulasi',
                'sub_category' => 'Manajemen Proyek',
                'author' => 'Divisi Manajemen Proyek',
                'excerpt' => 'Manajemen risiko adalah kunci keberhasilan proyek konstruksi skala besar.',
                'content' => '<p>Proyek besar memiliki risiko yang kompleks mulai dari finansial hingga teknis. Manajemen risiko yang sistematis sangat penting.</p><p>Insinyur proyek harus memiliki kompetensi dalam identifikasi, analisis, dan mitigasi risiko sejak tahap perencanaan.</p><p>"Proyek yang sukses bukan yang tidak memiliki risiko, tapi yang mampu mengelola risiko dengan baik," tegas ahli manajemen proyek.</p>',
                'image' => 'https://images.unsplash.com/photo-1486325212027-8081e485255e?w=800&q=80',
                'published_at' => now()->subDays(29),
                'is_active' => true,
            ],
            [
                'title' => 'Peran Insinyur dalam Pengembangan Transportasi Publik',
                'category' => 'artikel_teknik',
                'sub_category' => 'Transportasi',
                'author' => 'Dr. Eko Prasetyo',
                'excerpt' => 'Pengembangan transportasi publik membutuhkan integrasi berbagai disiplin teknik.',
                'content' => '<p>Transportasi publik modern seperti MRT, LRT, dan BRT membutuhkan integrasi teknik sipil, elektrikal, mekanikal, dan sistem.</p><p>Insinyur harus bekerja lintas disiplin untuk menciptakan sistem transportasi yang efisien, aman, dan nyaman bagi pengguna.</p><p>"Transportasi publik adalah tentang integrasi sistem, bukan hanya membangun infrastruktur," jelas pakar transportasi.</p>',
                'image' => 'https://images.unsplash.com/photo-1477959858617-67f85cf4f1df?w=800&q=80',
                'published_at' => now()->subDays(30),
                'is_active' => true,
            ],
            [
                'title' => 'AI dalam Quality Control Konstruksi',
                'category' => 'inovasi',
                'sub_category' => 'Teknologi',
                'author' => 'Dr. Fitri Handayani',
                'excerpt' => 'Kecerdasan buatan membantu meningkatkan akurasi quality control dalam proyek konstruksi.',
                'content' => '<p>AI dan computer vision digunakan untuk mendeteksi cacat konstruksi secara otomatis dan lebih akurat daripada inspeksi manual.</p><p>Teknologi ini mengurangi human error dan meningkatkan konsistensi dalam quality control proyek konstruksi.</p><p>"AI tidak menggantikan insinyur QC, tapi meningkatkan kemampuan mereka mendeteksi masalah," ungkap peneliti AI.</p>',
                'image' => 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=800&q=80',
                'published_at' => now()->subDays(31),
                'is_active' => true,
            ],
            [
                'title' => 'Sertifikasi Profesi Insinyur Indonesia 2024',
                'category' => 'regulasi',
                'sub_category' => 'Sertifikasi',
                'author' => 'Divisi Sertifikasi PII',
                'excerpt' => 'Program sertifikasi profesi insinyur kini mengadopsi standar internasional untuk meningkatkan kompetensi.',
                'content' => '<p>PII meluncurkan program sertifikasi profesi insinyur yang diselaraskan dengan standar internasional seperti Washington Accord dan Sydney Accord.</p><p>Program ini mencakup berbagai spesialisasi teknik: sipil, mesin, elektro, industri, dan lainnya. Sertifikasi ini diakui di berbagai negara.</p><p>"Sertifikasi internasional membuka peluang karir global bagi insinyur Indonesia," jelas Direktur Sertifikasi PII.</p>',
                'image' => 'https://images.unsplash.com/photo-1450101499163-c8848c66ca85?w=800&q=80',
                'published_at' => now()->subDays(32),
                'is_active' => true,
            ],
        ];

        foreach ($beritas as $berita) {
            Berita::create($berita);
        }
    }
}
