<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Event;

class EventSeeder extends Seeder
{
    public function run(): void
    {
        $events = [
            [
                'title' => 'Seminar Nasional Keinsinyuran 2025',
                'type' => 'seminar',
                'category' => 'nasional',
                'sub_category' => 'Infrastruktur & Pembangunan',
                'description' => 'Seminar nasional membahas peran insinyur dalam pembangunan infrastruktur berkelanjutan di Indonesia.',
                'content' => '<p>Seminar Nasional Keinsinyuran 2025 akan menghadirkan para pakar dan praktisi terkemuka di bidang keinsinyuran untuk membahas isu-isu strategis dalam pembangunan infrastruktur Indonesia.</p><p><strong>Topik yang akan dibahas:</strong></p><ul><li>Infrastruktur hijau dan berkelanjutan</li><li>Digitalisasi dalam dunia konstruksi</li><li>Standar keselamatan bangunan terkini</li></ul>',
                'image' => null,
                'event_date' => '2025-08-15 09:00:00',
                'location' => 'Jakarta Convention Center, Jakarta',
                'link' => 'https://pii.or.id/seminar-nasional-2025',
                'is_active' => true,
            ],
            [
                'title' => 'Pelatihan BIM (Building Information Modeling) Level 1',
                'type' => 'pelatihan',
                'category' => 'nasional',
                'sub_category' => 'Teknologi Konstruksi',
                'description' => 'Pelatihan intensif BIM untuk insinyur sipil dan arsitek yang ingin meningkatkan kompetensi digital mereka.',
                'content' => '<p>Pelatihan BIM Level 1 dirancang khusus untuk para profesional di bidang konstruksi yang ingin memahami dan mengimplementasikan Building Information Modeling dalam proyek mereka.</p><p><strong>Materi Pelatihan:</strong></p><ol><li>Pengenalan dan konsep dasar BIM</li><li>Software Revit untuk pemula</li><li>Kolaborasi tim berbasis BIM</li><li>Studi kasus proyek nyata</li></ol>',
                'image' => null,
                'event_date' => '2025-09-05 08:00:00',
                'location' => 'Gedung PII, Menteng, Jakarta Pusat',
                'link' => 'https://pii.or.id/pelatihan-bim-2025',
                'is_active' => true,
            ],
            [
                'title' => 'Konvensi Insinyur Internasional Asia Pacific 2025',
                'type' => 'konvensi',
                'category' => 'internasional',
                'sub_category' => 'Asia Pacific Engineering Forum',
                'description' => 'Konvensi tahunan insinyur se-Asia Pacific membahas tantangan dan peluang di era revolusi industri 4.0.',
                'content' => '<p>Konvensi Insinyur Internasional Asia Pacific 2025 merupakan ajang bergengsi yang mempertemukan para insinyur dari seluruh kawasan Asia Pacific.</p><p>Tahun ini mengangkat tema <strong>"Engineering for a Sustainable Future"</strong> dengan fokus pada:</p><ul><li>Energi terbarukan dan transisi energi</li><li>Smart city dan infrastruktur digital</li><li>Ketahanan terhadap perubahan iklim</li><li>Kolaborasi riset antar negara</li></ul>',
                'image' => null,
                'event_date' => '2025-10-20 08:00:00',
                'location' => 'Bali International Convention Centre, Bali',
                'link' => 'https://pii.or.id/konvensi-internasional-2025',
                'is_active' => true,
            ],
            [
                'title' => 'Pelatihan K3 (Keselamatan dan Kesehatan Kerja) untuk Insinyur',
                'type' => 'pelatihan',
                'category' => 'regional',
                'sub_category' => 'Keselamatan Kerja',
                'description' => 'Pelatihan K3 wajib bagi insinyur yang bekerja di lapangan untuk memastikan standar keselamatan kerja terpenuhi.',
                'content' => '<p>Keselamatan dan Kesehatan Kerja (K3) adalah aspek fundamental yang tidak boleh diabaikan oleh setiap insinyur lapangan. Pelatihan ini memberikan pemahaman komprehensif tentang regulasi K3 terbaru di Indonesia.</p><p><strong>Jadwal Pelatihan:</strong></p><ol><li>Hari 1: Regulasi K3 dan standar internasional</li><li>Hari 2: Identifikasi bahaya dan penilaian risiko</li><li>Hari 3: Praktik lapangan dan simulasi</li></ol>',
                'image' => null,
                'event_date' => '2025-07-10 08:00:00',
                'location' => 'Hotel Santika, Surabaya',
                'link' => null,
                'is_active' => true,
            ],
            [
                'title' => 'Webinar: Transformasi Digital di Industri Manufaktur Indonesia',
                'type' => 'seminar',
                'category' => 'online',
                'sub_category' => 'Industri 4.0',
                'description' => 'Webinar gratis membahas bagaimana insinyur manufaktur dapat beradaptasi dengan era digitalisasi industri.',
                'content' => '<p>Di era Industri 4.0, transformasi digital bukan lagi pilihan melainkan keharusan. Webinar ini akan membahas strategi dan langkah konkret bagi para insinyur manufaktur untuk menavigasi perubahan tersebut.</p><p><strong>Pembicara:</strong></p><ul><li>Ir. Budi Santoso, M.Eng - Direktur PT. Industri Nusantara</li><li>Dr. Siti Rahayu - Peneliti BRIN bidang Manufaktur Digital</li></ul><p>Webinar ini <strong>GRATIS</strong> untuk anggota PII aktif.</p>',
                'image' => null,
                'event_date' => '2025-06-25 13:00:00',
                'location' => 'Zoom Meeting (Online)',
                'link' => 'https://zoom.us/pii-webinar-2025',
                'is_active' => true,
            ],
            [
                'title' => 'Pelatihan Sertifikasi Insinyur Profesional (IP)',
                'type' => 'pelatihan',
                'category' => 'nasional',
                'sub_category' => 'Sertifikasi & Kompetensi',
                'description' => 'Program persiapan sertifikasi Insinyur Profesional (IP) untuk anggota PII yang ingin meningkatkan jenjang karir.',
                'content' => '<p>Sertifikasi Insinyur Profesional (IP) adalah pengakuan resmi atas kompetensi seorang insinyur dalam bidangnya. Program pelatihan ini dirancang untuk mempersiapkan peserta menghadapi ujian sertifikasi IP.</p><p><strong>Modul Pelatihan:</strong></p><ol><li>Etika profesi keinsinyuran</li><li>Standar dan regulasi teknis</li><li>Manajemen proyek engineering</li><li>Simulasi soal ujian IP</li><li>Sesi tanya jawab dengan penguji bersertifikat</li></ol><p>Peserta yang lulus akan mendapatkan <strong>sertifikat keikutsertaan</strong> dan dapat langsung mendaftar ujian IP resmi PII.</p>',
                'image' => null,
                'event_date' => '2025-11-08 08:00:00',
                'location' => 'Graha PII, Jakarta Selatan',
                'link' => 'https://pii.or.id/sertifikasi-ip-2025',
                'is_active' => true,
            ],
        ];

        foreach ($events as $eventData) {
            Event::create($eventData);
        }

        $moreEvents = [
            [
                'title' => 'Workshop Inovasi Infrastruktur Hijau',
                'type' => 'seminar',
                'category' => 'nasional',
                'sub_category' => 'Infrastruktur Berkelanjutan',
                'description' => 'Workshop membahas pendekatan terbaru dalam pembangunan infrastruktur yang ramah lingkungan dan berkelanjutan.',
                'content' => '<p>Workshop ini menghadirkan para pakar infrastruktur hijau dari seluruh Indonesia untuk berbagi pengetahuan dan praktik terbaik dalam membangun infrastruktur yang berkelanjutan.</p><ul><li>Green building standards dan sertifikasi</li><li>Material konstruksi ramah lingkungan</li><li>Manajemen energi pada bangunan</li><li>Studi kasus proyek sukses</li></ul>',
                'image' => 'https://images.unsplash.com/photo-1486325212027-8081e485255e?w=800&q=80',
                'event_date' => '2025-07-22 08:00:00',
                'location' => 'Bandung Convention Centre, Bandung',
                'link' => 'https://pii.or.id/workshop-infrastruktur-hijau',
                'is_active' => true,
            ],
            [
                'title' => 'Pelatihan Manajemen Proyek Konstruksi Level Lanjut',
                'type' => 'pelatihan',
                'category' => 'nasional',
                'sub_category' => 'Project Management',
                'description' => 'Pelatihan intensif 3 hari untuk meningkatkan kemampuan manajemen proyek konstruksi skala besar.',
                'content' => '<p>Program pelatihan lanjutan ini dirancang untuk insinyur berpengalaman yang ingin meningkatkan kompetensi dalam mengelola proyek konstruksi skala besar dan kompleks.</p><ol><li>Advanced scheduling dengan Primavera P6</li><li>Risk management dalam proyek konstruksi</li><li>Contract management dan klaim</li><li>Leadership dan team management</li></ol>',
                'image' => 'https://images.unsplash.com/photo-1504307651254-35680f356dfd?w=800&q=80',
                'event_date' => '2025-08-12 08:00:00',
                'location' => 'Hotel Pullman, Jakarta Pusat',
                'link' => 'https://pii.or.id/pelatihan-pm-lanjut',
                'is_active' => true,
            ],
            [
                'title' => 'Konvensi Tahunan Insinyur Sipil Indonesia 2025',
                'type' => 'konvensi',
                'category' => 'nasional',
                'sub_category' => 'Teknik Sipil',
                'description' => 'Konvensi tahunan untuk insinyur sipil membahas perkembangan terkini teknologi dan standar konstruksi.',
                'content' => '<p>Konvensi Tahunan Insinyur Sipil Indonesia 2025 adalah forum bergengsi yang mempertemukan ribuan insinyur sipil dari seluruh nusantara.</p><p>Tema tahun ini: <strong>"Resilient Infrastructure for Indonesia 2045"</strong></p><ul><li>Keynote dari Menteri PUPR</li><li>Panel diskusi pembangunan IKN</li><li>Pameran teknologi konstruksi terbaru</li><li>Networking session</li></ul>',
                'image' => 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&q=80',
                'event_date' => '2025-09-18 08:00:00',
                'location' => 'Surabaya Convention Hall, Surabaya',
                'link' => 'https://pii.or.id/konvensi-sipil-2025',
                'is_active' => true,
            ],
            [
                'title' => 'Webinar: AI dan Machine Learning untuk Insinyur',
                'type' => 'seminar',
                'category' => 'online',
                'sub_category' => 'Artificial Intelligence',
                'description' => 'Webinar gratis mengenai penerapan AI dan machine learning dalam berbagai bidang keinsinyuran.',
                'content' => '<p>Di era kecerdasan buatan, insinyur perlu memahami bagaimana AI dapat digunakan untuk meningkatkan efisiensi dan akurasi pekerjaan mereka.</p><p><strong>Yang akan dibahas:</strong></p><ul><li>Pengantar AI dan ML untuk non-programmer</li><li>Computer vision dalam inspeksi infrastruktur</li><li>Predictive maintenance dengan ML</li><li>Tools AI yang bisa langsung digunakan</li></ul>',
                'image' => 'https://images.unsplash.com/photo-1677442135703-1787eea5ce01?w=800&q=80',
                'event_date' => '2025-07-30 14:00:00',
                'location' => 'Google Meet (Online)',
                'link' => 'https://meet.google.com/pii-ai-webinar',
                'is_active' => true,
            ],
            [
                'title' => 'Pelatihan AutoCAD & Revit untuk Insinyur Mekanikal',
                'type' => 'pelatihan',
                'category' => 'regional',
                'sub_category' => 'CAD & BIM',
                'description' => 'Pelatihan software desain AutoCAD dan Revit khusus untuk insinyur di bidang mekanikal dan elektrikal.',
                'content' => '<p>Kuasai dua software desain paling populer di industri konstruksi dan manufaktur. Pelatihan ini mencakup dasar hingga tingkat mahir dalam penggunaan AutoCAD dan Revit untuk aplikasi mekanikal.</p><ol><li>AutoCAD 2D fundamentals</li><li>AutoCAD 3D modelling</li><li>Revit MEP basics</li><li>Koordinasi antar disiplin dengan BIM</li></ol>',
                'image' => 'https://images.unsplash.com/photo-1581092918056-0c4c3acd3789?w=800&q=80',
                'event_date' => '2025-08-05 08:00:00',
                'location' => 'Pusat Pelatihan PII, Semarang',
                'link' => null,
                'is_active' => true,
            ],
            [
                'title' => 'Forum Insinyur Muda Indonesia 2025',
                'type' => 'seminar',
                'category' => 'nasional',
                'sub_category' => 'Young Engineers',
                'description' => 'Forum tahunan khusus untuk insinyur muda berusia di bawah 35 tahun untuk berjejaring dan berbagi ide.',
                'content' => '<p>Forum Insinyur Muda Indonesia (FIMI) 2025 adalah ruang bagi generasi insinyur muda untuk saling terhubung, berbagi gagasan inovatif, dan merumuskan kontribusi nyata bagi kemajuan bangsa.</p><p><strong>Highlight acara:</strong></p><ul><li>Pitch kompetisi inovasi teknik</li><li>Mentoring dengan senior insinyur</li><li>Career development workshop</li><li>Networking dengan perusahaan top</li></ul>',
                'image' => 'https://images.unsplash.com/photo-1540575467063-178a50c2df87?w=800&q=80',
                'event_date' => '2025-10-04 08:00:00',
                'location' => 'Universitas Indonesia, Depok',
                'link' => 'https://pii.or.id/fimi-2025',
                'is_active' => true,
            ],
            [
                'title' => 'Pelatihan Teknik Geoteknik dan Pondasi',
                'type' => 'pelatihan',
                'category' => 'nasional',
                'sub_category' => 'Geoteknik',
                'description' => 'Pelatihan mendalam mengenai analisis tanah, desain pondasi, dan penanganan masalah geoteknik di lapangan.',
                'content' => '<p>Pelatihan Teknik Geoteknik dan Pondasi ini memberikan pemahaman komprehensif tentang perilaku tanah dan perancangan pondasi yang aman dan ekonomis.</p><ol><li>Klasifikasi dan sifat mekanis tanah</li><li>Penyelidikan lapangan dan laboratorium</li><li>Desain pondasi dangkal dan dalam</li><li>Stabilitas lereng dan dinding penahan</li><li>Studi kasus kegagalan geoteknik</li></ol>',
                'image' => 'https://images.unsplash.com/photo-1565793298595-6a879b1d9492?w=800&q=80',
                'event_date' => '2025-09-15 08:00:00',
                'location' => 'ITB, Bandung',
                'link' => 'https://pii.or.id/pelatihan-geoteknik',
                'is_active' => true,
            ],
            [
                'title' => 'Konvensi Insinyur Energi Terbarukan Indonesia',
                'type' => 'konvensi',
                'category' => 'nasional',
                'sub_category' => 'Energi Terbarukan',
                'description' => 'Konvensi khusus membahas transisi energi dan peran insinyur dalam mengakselerasi pengembangan energi terbarukan.',
                'content' => '<p>Indonesia memiliki potensi energi terbarukan yang sangat besar — matahari, angin, panas bumi, dan air. Konvensi ini membahas bagaimana insinyur dapat berkontribusi dalam percepatan transisi energi nasional.</p><ul><li>Update kebijakan energi terbarukan 2025</li><li>Teknologi PLTS skala utilitas</li><li>Offshore wind development</li><li>Energy storage solutions</li><li>Peluang karir di sektor EBT</li></ul>',
                'image' => 'https://images.unsplash.com/photo-1509391366360-2e959784a276?w=800&q=80',
                'event_date' => '2025-11-15 08:00:00',
                'location' => 'Nusa Dua Convention Center, Bali',
                'link' => 'https://pii.or.id/konvensi-ebt-2025',
                'is_active' => true,
            ],
            [
                'title' => 'Seminar Keselamatan Bendungan dan Infrastruktur Air',
                'type' => 'seminar',
                'category' => 'nasional',
                'sub_category' => 'Sumber Daya Air',
                'description' => 'Seminar teknis tentang keselamatan bendungan, pengelolaan risiko banjir, dan infrastruktur air bersih.',
                'content' => '<p>Dengan lebih dari 200 bendungan yang beroperasi di Indonesia, keselamatan bendungan menjadi isu kritis yang harus dipahami setiap insinyur bidang sumber daya air.</p><p><strong>Pembicara utama:</strong></p><ul><li>Direktur Bendungan Kementerian PUPR</li><li>Ahli hidrologi dari UNDIP</li><li>Konsultan internasional dari ICOLD</li></ul>',
                'image' => 'https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=800&q=80',
                'event_date' => '2025-08-28 09:00:00',
                'location' => 'Balai Teknik Sabo, Yogyakarta',
                'link' => 'https://pii.or.id/seminar-bendungan',
                'is_active' => true,
            ],
            [
                'title' => 'Pelatihan Inspeksi dan Pemeliharaan Jembatan',
                'type' => 'pelatihan',
                'category' => 'regional',
                'sub_category' => 'Jembatan & Jalan',
                'description' => 'Pelatihan praktis teknik inspeksi kondisi jembatan dan perencanaan program pemeliharaan yang efektif.',
                'content' => '<p>Indonesia memiliki ribuan jembatan yang perlu diinspeksi dan dipelihara secara berkala. Pelatihan ini membekali insinyur dengan kemampuan inspeksi yang terstandar sesuai Panduan Pemeriksaan Jembatan Kementerian PUPR.</p><ol><li>Sistem klasifikasi kondisi jembatan (BMS)</li><li>Teknik inspeksi visual dan instrumen</li><li>Identifikasi kerusakan beton dan baja</li><li>Perencanaan dan prioritasi pemeliharaan</li></ol>',
                'image' => 'https://images.unsplash.com/photo-1477959858617-67f85cf4f1df?w=800&q=80',
                'event_date' => '2025-10-14 08:00:00',
                'location' => 'Balai Jembatan, Makassar',
                'link' => null,
                'is_active' => true,
            ],
            [
                'title' => 'Webinar: Hukum Kontrak untuk Insinyur Lapangan',
                'type' => 'seminar',
                'category' => 'online',
                'sub_category' => 'Hukum & Regulasi',
                'description' => 'Webinar praktis membahas aspek hukum kontrak konstruksi yang wajib dipahami insinyur di lapangan.',
                'content' => '<p>Banyak insinyur lapangan yang tidak memahami hak dan kewajiban mereka dalam kontrak konstruksi. Webinar ini hadir untuk menjembatani kesenjangan tersebut.</p><p><strong>Topik yang dibahas:</strong></p><ul><li>Jenis-jenis kontrak konstruksi (FIDIC, SBD)</li><li>Hak dan kewajiban kontraktor & owner</li><li>Prosedur klaim dan dispute resolution</li><li>Studi kasus sengketa konstruksi nyata</li></ul>',
                'image' => 'https://images.unsplash.com/photo-1589829545856-d10d557cf95f?w=800&q=80',
                'event_date' => '2025-09-10 13:00:00',
                'location' => 'Zoom Webinar (Online)',
                'link' => 'https://zoom.us/pii-kontrak-webinar',
                'is_active' => true,
            ],
            [
                'title' => 'Pelatihan Desain Struktur Baja AISC & SNI',
                'type' => 'pelatihan',
                'category' => 'nasional',
                'sub_category' => 'Struktur Baja',
                'description' => 'Pelatihan komprehensif desain struktur baja mengacu standar AISC dan SNI terbaru.',
                'content' => '<p>Struktur baja semakin banyak digunakan dalam konstruksi modern Indonesia. Pelatihan ini memberikan pemahaman mendalam tentang perancangan elemen dan sistem struktur baja.</p><ol><li>Material baja struktural dan sifat mekanisnya</li><li>Desain balok, kolom, dan sambungan baut</li><li>Desain sambungan las</li><li>Pemodelan struktur dengan SAP2000/ETABS</li><li>Aplikasi SNI 1729:2020</li></ol>',
                'image' => 'https://images.unsplash.com/photo-1486325212027-8081e485255e?w=800&q=80',
                'event_date' => '2025-12-03 08:00:00',
                'location' => 'Hotel Santika Premiere, Jakarta',
                'link' => 'https://pii.or.id/pelatihan-struktur-baja',
                'is_active' => true,
            ],
            [
                'title' => 'Konvensi Insinyur Tambang dan Mineral',
                'type' => 'konvensi',
                'category' => 'nasional',
                'sub_category' => 'Pertambangan',
                'description' => 'Konvensi tahunan insinyur pertambangan membahas isu keberlanjutan, regulasi, dan teknologi terkini industri mining.',
                'content' => '<p>Industri pertambangan Indonesia menghadapi tantangan besar dalam era transisi energi dan tuntutan keberlanjutan. Konvensi ini mempertemukan para pemimpin industri untuk merumuskan arah ke depan.</p><ul><li>Update regulasi pertambangan 2025</li><li>Teknologi mine automation dan digitalisasi</li><li>ESG dalam operasi tambang</li><li>Mine closure dan rehabilitasi lahan</li></ul>',
                'image' => 'https://images.unsplash.com/photo-1578496479531-32e296d5c6e1?w=800&q=80',
                'event_date' => '2025-11-25 08:00:00',
                'location' => 'Kalimantan Convention Centre, Balikpapan',
                'link' => 'https://pii.or.id/konvensi-tambang-2025',
                'is_active' => true,
            ],
            [
                'title' => 'Workshop GIS untuk Perencanaan Infrastruktur',
                'type' => 'seminar',
                'category' => 'regional',
                'sub_category' => 'Geospasial & GIS',
                'description' => 'Workshop hands-on penggunaan GIS (Geographic Information System) untuk mendukung perencanaan dan monitoring infrastruktur.',
                'content' => '<p>GIS telah menjadi alat yang tidak terpisahkan dalam perencanaan infrastruktur modern. Workshop ini mengajarkan penggunaan QGIS dan ArcGIS secara praktis untuk aplikasi keinsinyuran.</p><ol><li>Dasar-dasar GIS dan data spasial</li><li>Analisis rute dan transportasi</li><li>Pemetaan risiko bencana</li><li>Monitoring kondisi infrastruktur berbasis GIS</li></ol>',
                'image' => 'https://images.unsplash.com/photo-1524661135-423995f22d0b?w=800&q=80',
                'event_date' => '2025-10-22 08:00:00',
                'location' => 'Institut Teknologi Sepuluh Nopember, Surabaya',
                'link' => 'https://pii.or.id/workshop-gis',
                'is_active' => true,
            ],
            [
                'title' => 'Pelatihan Pengujian Non-Destruktif (NDT)',
                'type' => 'pelatihan',
                'category' => 'nasional',
                'sub_category' => 'Quality Control',
                'description' => 'Pelatihan teknik pengujian non-destruktif untuk inspeksi material dan struktur tanpa merusak objek uji.',
                'content' => '<p>Non-Destructive Testing (NDT) adalah kemampuan krusial dalam quality control konstruksi dan inspeksi infrastruktur. Peserta akan mendapatkan sertifikat kompetensi NDT Level 1.</p><ol><li>Ultrasonic Testing (UT)</li><li>Radiographic Testing (RT)</li><li>Magnetic Particle Testing (MT)</li><li>Liquid Penetrant Testing (PT)</li><li>Visual Inspection (VT)</li></ol>',
                'image' => 'https://images.unsplash.com/photo-1581092921461-eab62e97a780?w=800&q=80',
                'event_date' => '2025-11-04 08:00:00',
                'location' => 'BPPT, Serpong, Tangerang Selatan',
                'link' => 'https://pii.or.id/pelatihan-ndt',
                'is_active' => true,
            ],
            [
                'title' => 'Seminar Nasional Smart City dan Infrastruktur Digital',
                'type' => 'seminar',
                'category' => 'nasional',
                'sub_category' => 'Smart City',
                'description' => 'Seminar membahas peran insinyur dalam mewujudkan kota cerdas melalui integrasi teknologi digital dan infrastruktur.',
                'content' => '<p>Lebih dari 100 kota di Indonesia sedang dalam proses transformasi menuju smart city. Seminar ini mendiskusikan tantangan teknis dan peluang bagi insinyur dalam ekosistem kota cerdas.</p><ul><li>Arsitektur sistem smart city</li><li>IoT sensor networks untuk infrastruktur</li><li>Data analytics untuk manajemen kota</li><li>Cybersecurity infrastruktur kritis</li><li>Case study: Surabaya Smart City</li></ul>',
                'image' => 'https://images.unsplash.com/photo-1573164713988-8665fc963095?w=800&q=80',
                'event_date' => '2025-12-10 09:00:00',
                'location' => 'Balai Kota Surabaya, Surabaya',
                'link' => 'https://pii.or.id/seminar-smart-city',
                'is_active' => true,
            ],
            [
                'title' => 'Pelatihan Estimasi Biaya Konstruksi (RAB)',
                'type' => 'pelatihan',
                'category' => 'regional',
                'sub_category' => 'Cost Engineering',
                'description' => 'Pelatihan penyusunan Rencana Anggaran Biaya (RAB) yang akurat dan sesuai standar Permen PUPR terbaru.',
                'content' => '<p>Kesalahan estimasi biaya dapat berakibat fatal bagi keberhasilan proyek. Pelatihan ini memberikan metodologi dan tools praktis untuk menyusun RAB yang akurat.</p><ol><li>Analisa Harga Satuan Pekerjaan (AHSP) terbaru</li><li>Metode volume take-off dari gambar</li><li>Software estimasi: Cubicost dan MS Excel</li><li>Contingency dan eskalasi harga</li><li>Latihan studi kasus proyek nyata</li></ol>',
                'image' => 'https://images.unsplash.com/photo-1554224155-6726b3ff858f?w=800&q=80',
                'event_date' => '2025-07-16 08:00:00',
                'location' => 'Hotel Aston, Medan',
                'link' => null,
                'is_active' => true,
            ],
            [
                'title' => 'Forum Insinyur Perempuan Indonesia',
                'type' => 'seminar',
                'category' => 'nasional',
                'sub_category' => 'Diversity & Inclusion',
                'description' => 'Forum tahunan untuk insinyur perempuan Indonesia membahas tantangan, peluang, dan kepemimpinan di dunia teknik.',
                'content' => '<p>Forum Insinyur Perempuan Indonesia (FIPI) hadir untuk memperkuat peran perempuan dalam ekosistem keinsinyuran nasional. Forum ini menghadirkan role model dan mentor berpengalaman.</p><ul><li>Keynote dari tokoh insinyur perempuan Indonesia</li><li>Panel diskusi: Perempuan di C-Suite industri teknik</li><li>Workshop: Leadership untuk insinyur perempuan</li><li>Mentoring 1-on-1 dengan senior engineer</li></ul>',
                'image' => 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=800&q=80',
                'event_date' => '2025-08-21 09:00:00',
                'location' => 'Hotel Mulia, Jakarta Selatan',
                'link' => 'https://pii.or.id/fipi-2025',
                'is_active' => true,
            ],
            [
                'title' => 'Pelatihan Pemodelan Struktur dengan SAP2000',
                'type' => 'pelatihan',
                'category' => 'online',
                'sub_category' => 'Structural Analysis Software',
                'description' => 'Pelatihan online intensif pemodelan dan analisis struktur menggunakan software SAP2000 dari dasar hingga mahir.',
                'content' => '<p>SAP2000 adalah salah satu software analisis struktur paling banyak digunakan di dunia. Pelatihan online ini memungkinkan Anda belajar dari rumah dengan mentor berpengalaman.</p><ol><li>Interface dan setup SAP2000</li><li>Pemodelan frame dan shell element</li><li>Pembebanan: gravitasi, angin, gempa (SNI 1726)</li><li>Analisis statik dan dinamik</li><li>Output dan interpretasi hasil</li><li>Desain elemen dengan code check</li></ol>',
                'image' => 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=800&q=80',
                'event_date' => '2025-09-22 09:00:00',
                'location' => 'Zoom Meeting (Online)',
                'link' => 'https://pii.or.id/pelatihan-sap2000',
                'is_active' => true,
            ],
            [
                'title' => 'Konvensi Insinyur Infrastruktur Transportasi',
                'type' => 'konvensi',
                'category' => 'internasional',
                'sub_category' => 'Transportasi & Mobilitas',
                'description' => 'Konvensi internasional membahas masa depan infrastruktur transportasi — jalan tol, kereta cepat, dan pelabuhan.',
                'content' => '<p>Indonesia sedang membangun infrastruktur transportasi besar-besaran. Konvensi ini mempertemukan para insinyur dan pemangku kepentingan untuk mendiskusikan inovasi dan tantangan ke depan.</p><ul><li>Update proyek strategis nasional (PSN) transportasi</li><li>Teknologi konstruksi jalan tol terkini</li><li>High-speed rail engineering</li><li>Pengembangan pelabuhan dan bandara</li><li>Integrasi moda transportasi</li><li>Sesi bilateral dengan delegasi asing</li></ul>',
                'image' => 'https://images.unsplash.com/photo-1474487548417-781cb71495f3?w=800&q=80',
                'event_date' => '2025-12-17 08:00:00',
                'location' => 'Jakarta International Expo, Jakarta',
                'link' => 'https://pii.or.id/konvensi-transportasi-2025',
                'is_active' => true,
            ],
            [
                'title' => 'Pelatihan Lean Construction untuk Proyek Efisien',
                'type' => 'pelatihan',
                'category' => 'nasional',
                'sub_category' => 'Project Management',
                'description' => 'Pelatihan metodologi Lean Construction untuk mengurangi waste dan meningkatkan efisiensi proyek.',
                'content' => '<p>Lean Construction adalah metodologi yang fokus pada minimasi waste dan maksimasi nilai dalam proyek konstruksi. Pelatihan ini mengajarkan prinsip dan tools Lean.</p><ol><li>Last Planner System</li><li>Value Stream Mapping</li><li>Target Value Design</li><li>Choosing by Advantages</li><li>Implementasi Lean di proyek nyata</li></ol>',
                'image' => 'https://images.unsplash.com/photo-1504307651254-35680f356dfd?w=800&q=80',
                'event_date' => '2025-07-18 08:00:00',
                'location' => 'Hotel Grand Hyatt, Jakarta',
                'link' => 'https://pii.or.id/pelatihan-lean-construction',
                'is_active' => true,
            ],
            [
                'title' => 'Seminar Teknologi Beton High-Performance',
                'type' => 'seminar',
                'category' => 'nasional',
                'sub_category' => 'Material Konstruksi',
                'description' => 'Seminar membahas perkembangan teknologi beton high-performance untuk struktur modern.',
                'content' => '<p>Beton high-performance (HPC) semakin banyak digunakan dalam proyek-proyek strategis Indonesia. Seminar ini membahas teknologi terbaru dan aplikasinya.</p><p><strong>Topik utama:</strong></p><ul><li>Self-compacting concrete (SCC)</li><li>Ultra-high performance concrete (UHPC)</li><li>Fiber-reinforced concrete</li><li>Durability dan life-cycle</li></ul>',
                'image' => 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&q=80',
                'event_date' => '2025-08-30 09:00:00',
                'location' => 'Universitas Gadjah Mada, Yogyakarta',
                'link' => 'https://pii.or.id/seminar-beton-hpc',
                'is_active' => true,
            ],
            [
                'title' => 'Webinar: Blockchain untuk Supply Chain Konstruksi',
                'type' => 'seminar',
                'category' => 'online',
                'sub_category' => 'Teknologi',
                'description' => 'Webinar gratis membahas potensi blockchain dalam transparansi dan efisiensi supply chain konstruksi.',
                'content' => '<p>Blockchain technology menawarkan potensi besar untuk meningkatkan transparansi dan efisiensi dalam supply chain konstruksi.</p><p><strong>Yang akan dibahas:</strong></p><ul><li>Dasar blockchain untuk non-teknis</li><li>Smart contracts dalam konstruksi</li><li>Tracking material dan quality assurance</li><li>Studi kasus implementasi</li></ul>',
                'image' => 'https://images.unsplash.com/photo-1639762681485-074b7f938ba0?w=800&q=80',
                'event_date' => '2025-09-25 14:00:00',
                'location' => 'Zoom Meeting (Online)',
                'link' => 'https://zoom.us/pii-blockchain-webinar',
                'is_active' => true,
            ],
            [
                'title' => 'Pelatihan Leadership untuk Insinyur Project Manager',
                'type' => 'pelatihan',
                'category' => 'nasional',
                'sub_category' => 'Leadership',
                'description' => 'Pelatihan leadership khusus untuk insinyur yang ingin menjadi project manager yang efektif.',
                'content' => '<p>Technical skills saja tidak cukup untuk menjadi project manager sukses. Pelatihan ini membekali insinyur dengan leadership skills yang diperlukan.</p><ol><li>Komunikasi efektif dengan stakeholder</li><li>Conflict resolution dalam tim</li><li>Decision making under pressure</li><li>Building high-performing teams</li><li>Emotional intelligence untuk leader</li></ol>',
                'image' => 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=800&q=80',
                'event_date' => '2025-10-08 08:00:00',
                'location' => 'Hotel Mulia, Jakarta',
                'link' => 'https://pii.or.id/pelatihan-leadership-pm',
                'is_active' => true,
            ],
            [
                'title' => 'Konvensi Insinyur Telekomunikasi Indonesia',
                'type' => 'konvensi',
                'category' => 'nasional',
                'sub_category' => 'Telekomunikasi',
                'description' => 'Konvensi tahunan insinyur telekomunikasi membahas perkembangan 5G dan infrastruktur digital.',
                'content' => '<p>Indonesia sedang mempercepat rollout 5G dan pengembangan infrastruktur digital nasional. Konvensi ini membahas tantangan teknis dan peluang bagi insinyur telekomunikasi.</p><ul><li>5G network architecture</li><li>Fiber optic deployment</li><li>Data center infrastructure</li><li>Satellite communication</li><li>Cybersecurity telecom networks</li></ul>',
                'image' => 'https://images.unsplash.com/photo-1558494949-ef010cbdcc31?w=800&q=80',
                'event_date' => '2025-11-20 08:00:00',
                'location' => 'Telkom HQ, Bandung',
                'link' => 'https://pii.or.id/konvensi-telekomunikasi-2025',
                'is_active' => true,
            ],
        ];

        $futureEvents = [
            [
                'title' => 'World Engineering Forum 2026',
                'type' => 'konvensi',
                'category' => 'internasional',
                'sub_category' => 'Global Engineering',
                'description' => 'Forum engineering dunia membahas solusi global untuk tantangan iklim dan energi.',
                'content' => '<p>World Engineering Forum 2026 akan menghadirkan pemimpin engineering dari seluruh dunia untuk membahas solusi kolaboratif terhadap tantangan global.</p><ul><li>Climate adaptation engineering</li><li>Global energy transition</li><li>Sustainable infrastructure</li><li>International collaboration frameworks</li></ul>',
                'image' => 'https://images.unsplash.com/photo-1540575467063-178a50c2df87?w=800&q=80',
                'event_date' => '2026-03-15 08:00:00',
                'location' => 'Singapore Expo, Singapore',
                'link' => 'https://wef2026.global',
                'is_active' => true,
            ],
            [
                'title' => 'Pelatihan AI untuk Insinyur Konstruksi',
                'type' => 'pelatihan',
                'category' => 'nasional',
                'sub_category' => 'Artificial Intelligence',
                'description' => 'Pelatihan intensif penerapan AI dalam proyek konstruksi modern.',
                'content' => '<p>Pelatihan ini dirancang untuk insinyur konstruksi yang ingin mengadopsi teknologi AI dalam pekerjaan sehari-hari.</p><ol><li>Computer vision untuk inspeksi</li><li>Predictive maintenance</li><li>AI untuk scheduling proyek</li><li>Machine learning untuk estimasi biaya</li></ol>',
                'image' => 'https://images.unsplash.com/photo-1677442136071-1787eea5ce01?w=800&q=80',
                'event_date' => '2026-04-10 08:00:00',
                'location' => 'Training Center PII, Jakarta',
                'link' => 'https://pii.or.id/pelatihan-ai-konstruksi',
                'is_active' => true,
            ],
            [
                'title' => 'Seminar: Future of Smart Cities in Indonesia',
                'type' => 'seminar',
                'category' => 'nasional',
                'sub_category' => 'Smart City',
                'description' => 'Seminar membahas visi Indonesia menuju 100 smart city pada 2030.',
                'content' => '<p>Indonesia menargetkan 100 smart city pada 2030. Seminar ini membahas roadmap dan implementasi teknologi yang diperlukan.</p><ul><li>IoT infrastructure</li><li>Smart transportation systems</li><li>Digital governance</li><li>Public-private partnerships</li></ul>',
                'image' => 'https://images.unsplash.com/photo-1573164713988-8665fc963095?w=800&q=80',
                'event_date' => '2026-05-22 09:00:00',
                'location' => 'Balai Kota Jakarta, Jakarta',
                'link' => 'https://pii.or.id/seminar-smart-city-2026',
                'is_active' => true,
            ],
            [
                'title' => 'Pelatihan Cybersecurity untuk Critical Infrastructure',
                'type' => 'pelatihan',
                'category' => 'nasional',
                'sub_category' => 'Cybersecurity',
                'description' => 'Pelatihan keamanan siber untuk insinyur yang mengelola infrastruktur kritis.',
                'content' => '<p>Infrastruktur kritis seperti PLN, pertamina, dan transportasi membutuhkan proteksi siber yang kuat. Pelatihan ini membahas best practices.</p><ol><li>Threat assessment</li><li>Incident response</li><li>Secure system design</li><li>Compliance and regulations</li></ol>',
                'image' => 'https://images.unsplash.com/photo-1550751827-4bd374c3f58b?w=800&q=80',
                'event_date' => '2026-06-18 08:00:00',
                'location' => 'Cybersecurity Training Center, BSD City',
                'link' => 'https://pii.or.id/pelatihan-cybersec',
                'is_active' => true,
            ],
            [
                'title' => 'Konvensi Insinyur Lingkungan Asia Pasifik',
                'type' => 'konvensi',
                'category' => 'internasional',
                'sub_category' => 'Environmental Engineering',
                'description' => 'Konvensi regional membahas solusi engineering untuk isu lingkungan Asia Pasifik.',
                'content' => '<p>Konvensi ini mempertemukan insinyur lingkungan dari seluruh Asia Pasifik untuk berbagi solusi terbaik dalam penanganan isu lingkungan.</p><ul><li>Wastewater treatment innovation</li><li>Air quality management</li><li>Solid waste solutions</li><li>Climate resilience engineering</li></ul>',
                'image' => 'https://images.unsplash.com/photo-1497436072909-60f360e1d4b1?w=800&q=80',
                'event_date' => '2026-07-20 08:00:00',
                'location' => 'Bali Nusa Dua Convention Center, Bali',
                'link' => 'https://apiee2026.org',
                'is_active' => true,
            ],
            [
                'title' => 'Webinar: Quantum Computing untuk Insinyur',
                'type' => 'seminar',
                'category' => 'online',
                'sub_category' => 'Quantum Technology',
                'description' => 'Webinar pengenalan quantum computing dan potensi aplikasinya dalam engineering.',
                'content' => '<p>Quantum computing akan mengubah landscape engineering dalam dekade mendatang. Webinar ini memberikan pengantar untuk insinyur.</p><p><strong>Topik:</strong></p><ul><li>Quantum basics for engineers</li><li>Quantum algorithms for optimization</li><li>Applications in materials science</li><li>Future prospects</li></ul>',
                'image' => 'https://images.unsplash.com/photo-1635070041078-e363dbe005cb?w=800&q=80',
                'event_date' => '2026-08-15 14:00:00',
                'location' => 'Zoom Webinar (Online)',
                'link' => 'https://zoom.us/pii-quantum',
                'is_active' => true,
            ],
            [
                'title' => 'Pelatihan Project Management Digital',
                'type' => 'pelatihan',
                'category' => 'nasional',
                'sub_category' => 'Digital PM',
                'description' => 'Pelatihan manajemen proyek berbasis digital dengan tools modern.',
                'content' => '<p>Manajemen proyek modern membutuhkan tools digital untuk efisiensi maksimal. Pelatihan ini mengajarkan penggunaan berbagai PM tools.</p><ol><li>Jira and Confluence</li><li>Microsoft Project Online</li><li>Asana for engineering projects</li><li>Collaboration platforms</li></ol>',
                'image' => 'https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?w=800&q=80',
                'event_date' => '2026-09-12 08:00:00',
                'location' => 'Digital Training Hub, Jakarta',
                'link' => 'https://pii.or.id/pelatihan-digital-pm',
                'is_active' => true,
            ],
            [
                'title' => 'Seminar: Hydrogen Economy dan Peran Insinyur',
                'type' => 'seminar',
                'category' => 'nasional',
                'sub_category' => 'Energi',
                'description' => 'Seminar membahas ekonomi hidrogen dan peluang bagi insinyur Indonesia.',
                'content' => '<p>Hidrogen hijau adalah masa depan energi bersih. Seminar ini membahas peluang dan tantangan dalam ekonomi hidrogen Indonesia.</p><ul><li>Green hydrogen production</li><li>Infrastructure requirements</li><li>Policy and regulations</li><li>Career opportunities in hydrogen sector</li></ul>',
                'image' => 'https://images.unsplash.com/photo-1597424456583-7a2b637aeb49?w=800&q=80',
                'event_date' => '2026-10-25 09:00:00',
                'location' => 'Energy Building, Jakarta',
                'link' => 'https://pii.or.id/seminar-hydrogen',
                'is_active' => true,
            ],
            [
                'title' => 'Pelatihan 3D Printing untuk Konstruksi',
                'type' => 'pelatihan',
                'category' => 'nasional',
                'sub_category' => 'Advanced Manufacturing',
                'description' => 'Pelatihan teknologi 3D printing dalam konstruksi dan manufaktur.',
                'content' => '<p>3D printing atau additive manufacturing mengubah cara kita membangun. Pelatihan ini mengajarkan aplikasi praktis dalam konstruksi.</p><ol><li>Concrete 3D printing</li><li>Material selection</li><li>Design for additive manufacturing</li><li>Case studies and hands-on</li></ol>',
                'image' => 'https://images.unsplash.com/photo-1563872263814-8a549ea66981?w=800&q=80',
                'event_date' => '2026-11-08 08:00:00',
                'location' => 'Advanced Manufacturing Lab, Bandung',
                'link' => 'https://pii.or.id/pelatihan-3d-printing',
                'is_active' => true,
            ],
            [
                'title' => 'Konvensi Insinyur Masa Depan 2027',
                'type' => 'konvensi',
                'category' => 'nasional',
                'sub_category' => 'Future Engineering',
                'description' => 'Konvensi visioner membahas masa depan profesi keinsinyuran Indonesia 2045.',
                'content' => '<p>Konvensi ini merumuskan visi dan strategi profesi keinsinyuran Indonesia menuju Golden Indonesia 2045.</p><ul><li>Engineering education transformation</li><li>Skill requirements for 2045</li><li>Industry 5.0 readiness</li><li>Sustainable development goals</li><li>Youth leadership development</li></ul>',
                'image' => 'https://images.unsplash.com/photo-1517245386807-bb43f82c33c4?w=800&q=80',
                'event_date' => '2027-01-20 08:00:00',
                'location' => 'Indonesia Convention Exhibition, Jakarta',
                'link' => 'https://pii.or.id/konvensi-future-2027',
                'is_active' => true,
            ],
        ];

        foreach ($moreEvents as $eventData) {
            Event::create($eventData);
        }

        foreach ($futureEvents as $eventData) {
            Event::create($eventData);
        }
    }
}
